#pragma once

#define TAPPING_TERM 300

#define EE_HANDS
#define SPLIT_USB_DETECT

#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1

#define MATRIX_ROWS 6
#define MATRIX_COLS 12

#define MATRIX_ROW_PINS {GP6, GP8, GP7}
#define MATRIX_COL_PINS {GP9, GP10, GP11, GP12, GP13, GP5}

#define MATRIX_ROW_PINS_RIGHT {GP26, GP15, GP14}
#define MATRIX_COL_PINS_RIGHT {GP8, GP9, GP10, GP11, GP12, GP27}
