include_dir=/nix/store/mmkh2v78liwvll9ikdamv3iqwy5drm1g-gcc-arm-embedded-15.2.rel1/arm-none-eabi/include
sys_include_dir=/nix/store/mmkh2v78liwvll9ikdamv3iqwy5drm1g-gcc-arm-embedded-15.2.rel1/arm-none-eabi/include
crt_dir=/nix/store/mmkh2v78liwvll9ikdamv3iqwy5drm1g-gcc-arm-embedded-15.2.rel1/arm-none-eabi/lib
msvc_lib_dir=
kernel32_lib_dir=
gcc_dir=
